driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: debian-7
  driver:
    image: debian:7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release procps -y

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release -y

- name: centos-5
  driver:
    image: centos:5
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum install -y which initscripts

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which systemd-sysv initscripts

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which systemd-sysv initscripts

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: opensuse-13.2
  driver:
    image: opensuse:13.2
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive which net-tools

- name: opensuse-42.1
  driver:
    image: opensuse:42.1
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive which hostname

suites:
  #
  # mysql2_chef_gem
  #
  - name: client50-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.0'
       provider: 'mysql'
    includes: [
      'centos-5'
    ]

  - name: client51-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.1'
       provider: 'mysql'
    includes: [
      'centos-6',
    ]

  - name: client55-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.5'
       provider: 'mysql'
    includes: [
      'centos-6',
      'ubuntu-12.04',
      'ubuntu-14.04'
    ]

  - name: client56-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.6'
       provider: 'mysql'
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'ubuntu-14.04'
    ]

  - name: client57-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.7'
       provider: 'mysql'
    includes: [
      'centos-5',
      'centos-6',
      'centos-7'
    ]

## MariaDB
  - name: client55-mariadb
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
        provider: 'mariadb'
      mariadb:
       install:
        version: '5.5'
    includes: [
      'ubuntu-14.04'
    ]
