settings:
  parallel: true

driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

platforms:
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    run_command: /usr/lib/systemd/systemd
    provision_command:
      - /bin/yum install -y initscripts net-tools wget

suites:
  #
  # mysql2_chef_gem
  #

  - name: client57-mysql
    run_list:
    - recipe[mysql2_chef_gem_test::default]
    attributes:
      mysql2_chef_gem:
       client_version: '5.7'
       provider: 'mysql'
    includes: [
      'centos-7'
    ]

