name 'mysql2_chef_gem'
maintainer 'Nicolas Blanc'
maintainer_email 'sinfomicien@gmail.com'
license 'Apache 2.0'
description 'Provides the mysql2_chef_gem resource'

version '0.1.0'

supports 'amazon'
supports 'redhat'
supports 'centos'
supports 'scientific'
supports 'fedora'
supports 'debian'
supports 'ubuntu'
supports 'smartos'

depends 'build-essential'
depends 'mysql'
depends 'mariadb'
